#!/bin/bash
if [[ $(echo $DESKTOP_SESSION) = "/usr/share/xsessions/plasma" ]]
	then 	
		konsole -e "vim $1 $2"
if [[ $(echo $DESKTOP_SESSION) = "/usr/share/xsessions/xfce" ]]
		xfce4-terminal -e "vim $1 $2"
	fi
